### ISSUE TITLE
[1.12.2] Singularity Duplication

### ISSUE THREAD

**Issue by Bulldogg6404** [Morpheus1101/Avaritia#127]
(apologies for originally posting this in the 1.7.10 github, this is where it belongs)

The neutronium compressor can be cheesed into producing difficult singularities using the materials for an easy singularity. If you create a singularity of one type, but start a second one of a different type without withdrawing the first, you can complete the second singularity and it will produce another singularity of the first type. 

![image](https://user-images.githubusercontent.com/6835872/50544338-87656280-0bb7-11e9-8e66-ca4b0dd06cca.png)

This can be done for any of the singularities, but is most notably the best way to demolish the Fluxed Electrum singularity, which is far and away the most daunting one to accomplish otherwise. I was able to build a simple machine to replicate tons of redstone blocks (thanks ProjectE), which I then dumped into a compressor I had primed with a Fluxed Electrum singularity, allowing me to bypass all the time and hassle of processing more than a single singularity's worth of Fluxed Electrum.

**Comment by Bulldogg6404** [comment]
> https://puu.sh/CpaCq/8638527c73.png
> 
> https://puu.sh/CpaD0/956d5257df.png
> 
> If your running a modpack with this in, id suggest contacting the modpack author.

Your images suggest that the bug could still be reproduced on your end, if you were to add more redstone blocks until it reaches the required amount to finish the second singularity. Is the stack in the input slot not being processed? If so, then I agree, it would be a conflict with a different mod.

**Comment by Morpheus1101** [comment]
i've tried this on my test world with creative chest things form thermal(caches i think there called) and i couldnt reproduce on any an did have all singularities hooked up to be produced and no matter what resource i add into the slot, if it isnt the correct one for the singularity being created, it will not process the resource.

**Comment by Bulldogg6404** [comment]
I took out all the mods except Avaritia, and was able to reproduce, as shown. I am unsure what you are doing different from me, but since Avaritia is the only mod installed for this world, I am left to conclude that it is not a conflict with some other mod.
![image](https://user-images.githubusercontent.com/6835872/50547111-08911980-0bf9-11e9-8cd8-6e20314e65a4.png)

**Comment by Bulldogg6404** [comment]
Detailed step-by-step reproduction of the issue. Note that the first lapis singularity is never removed from the compressor.
![image](https://user-images.githubusercontent.com/6835872/50547383-64aa6c80-0bfe-11e9-9cd7-76742cfe45b2.png)

**Comment by Morpheus1101** [comment]
Ok, i see what your referring to now.

**Comment by Morpheus1101** [comment]
Fixed in 3.3.0.30

**Comment by ninjakiwimartin** [comment]
Hello,

In 3.3.0.30 the bug is still happening. I start out by placing a single diamond block so the machine has the goal of crafting a diamond singulairty, and then dump in a huge amount of other blocks and they will count towards the diamond singularity progression. I tested it in both survival and creative, both yield the same results. I am using avaritia in combination with:

Draconic Evolution
Iron Chests
JEI
Loot Bags
Vein Miner

Hope this helps.

**Comment by Morpheus1101** [comment]
Ohh my, yes this indeed does occur an is a different bug thats cropped up by fixing the prev. Fix should be out soon

**Comment by Morpheus1101** [comment]
Fixed in 3.3.0.33
